context: fix tests when no secrets in default location
The tests were relying on the local user having an Upspin user set up with keys
in the default place ($HOME/.ssh). When setting up a new machine, I saw failures
like this:

--- FAIL: TestInitContext (0.00s)
	initcontext_test.go:227: could not parse config username: p@google.com
		keyserver: inprocess
		storeserver: remote,who.knows:1234
		dirserver: remote,who.knows:1234
		packing: ee
		: context.InitContext: item does not exist:
			factotum.NewFromDir:
			factotum.NewFromDir: open /Users/adg/.ssh/secret.upspinkey: no such file or directory

This CL fixes those failures by using secrets available from the Upspin tree.

Update issue #98.

Change-Id: Ib022daf841df658eb210cf53934d691ccffa5af6
Reviewed-on: https://upspin-review.googlesource.com/6282
Reviewed-by: Eric Grosse <ehg@google.com>