Update patch set 2
Patch Set 2:

> Patch Set 2:
> 
> (1 comment)
> 
> > Patch Set 2:
> > 
> > (3 comments)
> > 
> > something is not right here... still looking.
> 
> I don't see errors at head unless I run with -race on. Is the race in the test the only thing you're trying to fix or did something else prompted you to do this? Perhaps failures elsewhere?

No, this CL is about fixing the races in the tests so that the tests pass with -race.

What I'm doing here is taking out the global testing stubs and passing them into newPerm instead, so that each test has its own set of testing stubs.

The log.Clone error is actually benign as far as the tests are concerned; that just seems wrong.

The real issue is that after this change TestStoreIncludeRemoteGroups fails with a failure that I have been unable to diagnose:

--- FAIL: TestStoreIncludeRemoteGroups (0.38s)
	store_test.go:159: user "all@upspin.io" is allowed; expected not allowed
	store_test.go:159: user "foo@bar.com" is allowed; expected not allowed
	store_test.go:159: user "god@heaven.infinite" is allowed; expected not allowed
	store_test.go:159: user "nobody@nobody.org" is allowed; expected not allowed
FAIL

Patch-set: 2
Reviewer: Andrew Gerrand <5389@0759ed4b-3fdc-34dc-866b-f2e708168c03>