test/testfixtures: add Flags method to *simpleConfig
Fixes build failure caused by https://upspin-review.googlesource.com/c/9480/:

	$ go build upspin.io/...
	# upspin.io/test/testfixtures
	test/testfixtures/simpleconfig.go:21: cannot use simpleConfig literal (type *simpleConfig) as type upspin.Config in return argument:
		*simpleConfig does not implement upspin.Config (missing Flags method)

Change-Id: Iae088368954fac0e767c8b88a74ca469f926074b