Update patch set 3
Patch Set 3:

> Patch Set 3:
> 
> (1 comment)

Normally, I'd agree, but since the test wasn't being run, running most of it is better than none. But if it's an easy fix, I can do it. I will look at it now.

Both inprocess and server fail. It's probably an access package issue:

--- FAIL: TestIntegration (6.55s)
    --- FAIL: TestIntegration/kind=inprocess (0.39s)
        --- FAIL: TestIntegration/kind=inprocess/packing=plain (0.13s)
            --- FAIL: TestIntegration/kind=inprocess/packing=plain/WriteReadAllAccessFile (0.09s)
            	access_test.go:637: access_test.go:635: test@upspin.io/dir/Access: client.Put: cannot add "read:all" permission to existing files
        --- FAIL: TestIntegration/kind=inprocess/packing=eeintegrity (0.13s)
            --- FAIL: TestIntegration/kind=inprocess/packing=eeintegrity/WriteReadAllAccessFile (0.08s)
            	access_test.go:637: access_test.go:635: test@upspin.io/dir/Access: client.Put: cannot add "read:all" permission to existing files
        --- FAIL: TestIntegration/kind=inprocess/packing=ee (0.14s)
            --- FAIL: TestIntegration/kind=inprocess/packing=ee/WriteReadAllAccessFile (0.09s)
            	access_test.go:637: access_test.go:635: test@upspin.io/dir/Access: client.Put: cannot add "read:all" permission to existing files
    --- FAIL: TestIntegration/kind=server (6.16s)
        --- FAIL: TestIntegration/kind=server/packing=plain (2.09s)
            --- FAIL: TestIntegration/kind=server/packing=plain/WriteReadAllAccessFile (1.04s)
            	access_test.go:637: access_test.go:635: test@upspin.io/dir/Access: client.Put: cannot add "read:all" permission to existing files
        --- FAIL: TestIntegration/kind=server/packing=eeintegrity (2.10s)
            --- FAIL: TestIntegration/kind=server/packing=eeintegrity/WriteReadAllAccessFile (1.19s)
            	access_test.go:637: access_test.go:635: test@upspin.io/dir/Access: client.Put: cannot add "read:all" permission to existing files
        --- FAIL: TestIntegration/kind=server/packing=ee (1.98s)
            --- FAIL: TestIntegration/kind=server/packing=ee/WriteReadAllAccessFile (0.97s)
            	access_test.go:637: access_test.go:635: test@upspin.io/dir/Access: client.Put: cannot add "read:all" permission to existing files

Patch-set: 3
Reviewer: Eduardo Pinheiro <5308@0759ed4b-3fdc-34dc-866b-f2e708168c03>