pack: add countersign to packers besides ee
Promote Countersign function to the Pack interface and implement
in plain and eeintegrity. (It was only implemented in ee before.)
Add test for ee Countersign.

As far as I know, this introduces no new test complaints, but I
am seeing the following, which I think is unrelated to my change:
2017/04/07 18:07:00.547018 watch: sending error to client: dir/server/tree.sendEventFromLog: invalid operation: cannot read log at order 777: dir/server/tree.Log.Read: I/O error:
	dir/server/tree.LogEntry.unmarshal: Unmarshal buffer too short
2017/04/07 18:07:00.547343 watch: sending error to client: dir/server/tree.sendEventFromLog: invalid operation: cannot read log at order 777: dir/server/tree.Log.Read: I/O error:
	dir/server/tree.LogEntry.unmarshal: Unmarshal buffer too short
2017/04/07 18:07:01.594663 Created root: test+snapshot@upspin.io/
2017/04/07 18:07:01.599946 dir/server: Snapshotted "test@upspin.io/" into "test+snapshot@upspin.io/2017/04/07/18:07"
--- FAIL: TestIntegration (22.43s)

There is some further cleanup I see to do, and maybe some restructing
of the test, but let's get the #360 fix checked in first.

Fixes #360

Change-Id: I77e042328fb19458840245549aa0017259301ecc