Update patch set 6
Patch Set 6:

This change broke the dir/server tests.


$ go test
2017/04/03 22:24:18.854819 Created root: fred@flintstone.org/
2017/04/03 22:24:18.855837 Deleting root "fred@flintstone.org/"
--- FAIL: TestMakeRoot (0.02s)
	all_test.go:85: fred@flintstone.org/: dir/server.Delete: I/O error:
			dir/server/tree.DeleteLogs: remove /var/folders/2r/2wscqnf957d_75ltvpj_n4zc0035qk/T/DirServer712593847/tree.log.fred@flintstone.org: no such file or directory
2017/04/03 22:24:18.857052 Created root: wilma@flintstone.org/
--- FAIL: TestPut (0.00s)
	all_test.go:127: fred@flintstone.org/file1.txt: dir/server.Put: item does not exist:
			user fred@flintstone.org: dir/server/tree.LogIndex.Root: no root for user
--- FAIL: TestMakeDirectory (0.00s)
	all_test.go:145: fred@flintstone.org/dir: dir/server.Put: item does not exist:
			user fred@flintstone.org: dir/server/tree.LogIndex.Root: no root for user
--- FAIL: TestLink (0.00s)
	all_test.go:179: fred@flintstone.org/mylink: dir/server.Put: item does not exist:
			user fred@flintstone.org: dir/server/tree.LogIndex.Root: no root for user
--- FAIL: TestWhichAccess (0.00s)
	all_test.go:275: fred@flintstone.org/Access: dir/server.Put: item does not exist:
			user fred@flintstone.org: dir/server/tree.LogIndex.Root: no root for user
--- FAIL: TestHasRight (0.00s)
	all_test.go:332: fred@flintstone.org/Access: dir/server.Put: item does not exist:
			user fred@flintstone.org: dir/server/tree.LogIndex.Root: no root for user
--- FAIL: TestGlobDoesNotRemoveRoot (0.00s)
	all_test.go:371: dir/server.Glob: item does not exist:
			fred@flintstone.org/:
			dir/server.listDir:
			dir/server/tree.Flush:
			user fred@flintstone.org: dir/server/tree.LogIndex.Root: no root for user
2017/04/03 22:24:18.860727 Created root: joe@somewhere.com/
--- FAIL: TestGlob (0.00s)
	all_test.go:444: fred@flintstone.org/Access: dir/server.Put: item does not exist:
			user fred@flintstone.org: dir/server/tree.LogIndex.Root: no root for user
--- FAIL: TestDeletePermission (0.00s)
	all_test.go:702: fred@flintstone.org/Access: dir/server.Put: item does not exist:
			user fred@flintstone.org: dir/server/tree.LogIndex.Root: no root for user
--- FAIL: TestDelete (0.00s)
	all_test.go:744: err = dir/server/tree.Delete: item does not exist:
			user fred@flintstone.org: dir/server/tree.LogIndex.Root: no root for user, want = directory not empty
--- FAIL: TestForgetsRemoteGroupFiles (0.00s)
	all_test.go:782: fred@flintstone.org/Access: dir/server.Put: item does not exist:
			user fred@flintstone.org: dir/server/tree.LogIndex.Root: no root for user
--- FAIL: TestPermissionDenied (0.00s)
	all_test.go:841: fred@flintstone.org/Access: dir/server.Put: item does not exist:
			user fred@flintstone.org: dir/server/tree.LogIndex.Root: no root for user
--- FAIL: TestOverwriteFileWithWrongSequence (0.00s)
	all_test.go:882: fred@flintstone.org/Access: dir/server.Put: item does not exist:
			user fred@flintstone.org: dir/server/tree.LogIndex.Root: no root for user
--- FAIL: TestPutBadGroup (0.00s)
	all_test.go:916: fred@flintstone.org/Group: dir/server.Put: item does not exist:
			user fred@flintstone.org: dir/server/tree.LogIndex.Root: no root for user
2017/04/03 22:24:18.867479 Created root: bambi@forest.earth/
2017/04/03 22:24:18.869227 Created root: bambi+snapshot@forest.earth/
2017/04/03 22:24:18.873389 dir/server: Snapshotted "bambi@forest.earth/" into "bambi+snapshot@forest.earth/2017/01/02/01:00"
2017/04/03 22:24:18.877731 dir/server: Snapshotted "bambi@forest.earth/" into "bambi+snapshot@forest.earth/2017/01/02/14:00"
2017/04/03 22:24:18.881664 dir/server: Snapshotted "bambi@forest.earth/" into "bambi+snapshot@forest.earth/2017/01/02/17:01"
2017/04/03 22:24:18.883798 dir/server: Snapshotted "bambi@forest.earth/" into "bambi+snapshot@forest.earth/2017/01/02/17:02"
2017/04/03 22:24:18.887398 dir/server: Snapshotted "bambi@forest.earth/" into "bambi+snapshot@forest.earth/2017/01/02/17:03"
2017/04/03 22:24:18.891159 dir/server: Snapshotted "bambi@forest.earth/" into "bambi+snapshot@forest.earth/2017/01/02/17:13"
2017/04/03 22:24:18.904490 Created root: user+snapshot@example.com/
FAIL
exit status 1
FAIL	upspin.io/dir/server	0.091s

Patch-set: 6
CC: Andrew Gerrand <5389@0759ed4b-3fdc-34dc-866b-f2e708168c03>