Update patch set 3
Patch Set 3:

When I patch this into my tree on my workstation and run

 go test -short upspin.io/test

It gives me this error:

--- FAIL: TestIntegration (45.19s)
    --- FAIL: TestIntegration/kind=server (18.87s)
        --- FAIL: TestIntegration/kind=server/packing=eeintegrity (6.29s)
        	integration_test.go:376: remove /var/folders/2r/2wscqnf957d_75ltvpj_n4zc0035qk/T/testenv-dirserver990248892: directory not empty
        --- FAIL: TestIntegration/kind=server/packing=ee (6.29s)
        	integration_test.go:376: remove /var/folders/2r/2wscqnf957d_75ltvpj_n4zc0035qk/T/testenv-dirserver566772715: directory not empty
FAIL

I can't see any obvious cause for this, but I don't think we should check in a regression either, especially when we're so close to cleaning up our flaky tests. Can you think of a reason why this might be happening? Very strange.

Patch-set: 3
Reviewer: Andrew Gerrand <5389@0759ed4b-3fdc-34dc-866b-f2e708168c03>