cmd/upspin: add rekey tests
DO NOT REVIEW

This broken CL refines my question from yesterday.  Why does this
fail with the message
--- FAIL: TestCommands/ann_rekeys_and_countersigns (0.02s)
 cmd_test.go:187: "ann rekeys and countersigns": unexpected error:
  "upspin: test: no prior keys exist; cannot rotate keys

No need to review yet.  I may be able to figure this out on my own
by studying upbox further. But of course if you can hit me with a
clue stick in the meantime, great.

Change-Id: I728f194aa1d97bda70bac6320925114c851305f0