Update patch set 7
Patch Set 7:

CL 9640 fixed the build, but the TestSetFlagValues test is failing in Travis (https://travis-ci.org/upspin/upspin/builds/233069707) and for me locally:

	$ go test upspin.io/config
	--- FAIL: TestSetFlagValues (0.00s)
		initconfig_test.go:139: could not parse config 
			cmdflags:
			 cacheserver:
			  cachesize: 4000000000
			  writethrough: true
			: config.InitConfig: item does not exist:
				factotum.NewFromDir:
				factotum.NewFromDir: open /Users/Dmitri/.ssh/secret.upspinkey: no such file or directory
	FAIL
	FAIL	upspin.io/config	0.036s

It should probably not depend on $HOME/.ssh contents to pass.

Patch-set: 7