Update patch set 2
Patch Set 2:

> Patch Set 2:
> 
> > Patch Set 2:
> > 
> > > Patch Set 2:
> > > 
> > > (1 comment)
> > > 
> > > > Patch Set 2:
> > > > 
> > > > (3 comments)
> > > > 
> > > > something is not right here... still looking.
> > > 
> > > I don't see errors at head unless I run with -race on. Is the race in the test the only thing you're trying to fix or did something else prompted you to do this? Perhaps failures elsewhere?
> > 
> > No, this CL is about fixing the races in the tests so that the tests pass with -race.
> > 
> > What I'm doing here is taking out the global testing stubs and passing them into newPerm instead, so that each test has its own set of testing stubs.
> > 
> > The log.Clone error is actually benign as far as the tests are concerned; that just seems wrong.
> > 
> > The real issue is that after this change TestStoreIncludeRemoteGroups fails with a failure that I have been unable to diagnose:
> > 
> > --- FAIL: TestStoreIncludeRemoteGroups (0.38s)
> > 	store_test.go:159: user "all@upspin.io" is allowed; expected not allowed
> > 	store_test.go:159: user "foo@bar.com" is allowed; expected not allowed
> > 	store_test.go:159: user "god@heaven.infinite" is allowed; expected not allowed
> > 	store_test.go:159: user "nobody@nobody.org" is allowed; expected not allowed
> > FAIL
> 
> Ok, inspecting it again now.

Found the issue.

newWithEnv assumes you're self-contained with dir and store known -- you're giving the lookupFunc as the owner's DirServer. In reality, the lookup function needs to be generic. It needs to call DirServerFor.

Let me find a clean way of breaking this up.

I think we may not need lookup and watch functions anymore...

Patch-set: 2