dir/gcp: use new errors.Match function to clean up tests for golden errors
There is more to do here but it's cleaner now.

A failure now looks like this:

	--- FAIL: TestPutFileOverwritesDir (0.00s)
	all_test.go:422: Put: error mismatch: got test@foo.com/mydir/myfile.txt: Put: item already exists: directory already exists; want Put: item does not exist

So both errors are reported, and the output includes the line number
of the call to errors.Match+1, making it easy to find the problem. The old test
reported only line 83, the site of the assert call.

Update #30.

Change-Id: Ic84ea510e3a595566d15e7fea97382586bbc839a