Update patch set 7
Patch Set 7:

This change is causing a build error in upspin.io/test/testfixtures package:

	test/testfixtures/simpleconfig.go:21: cannot use simpleConfig literal (type *simpleConfig) as type upspin.Config in return argument:
		*simpleConfig does not implement upspin.Config (missing Flags method)

Patch-set: 7
CC: Gerrit User 5770 <5770@0759ed4b-3fdc-34dc-866b-f2e708168c03>