Update patch set 7
Patch Set 7:

> Patch Set 6:
> 
> The Travis CI build failed: https://travis-ci.org/AugieBot/upspin/builds/374221516?utm_source=github_status&utm_medium=notification

Hmm, this is an odd one. A dir/server failure:

--- FAIL: TestForgetsRemoteGroupFiles (0.12s)
	all_test.go:763: err = %!s(<nil>), want = "information withheld"
2018/05/03 01:53:29.323435 dir/server: Snapshotted "bambi@forest.earth/" into "bambi+snapshot@forest.earth/2017/01/02/01:00"
2018/05/03 01:53:29.334967 dir/server: Snapshotted "bambi@forest.earth/" into "bambi+snapshot@forest.earth/2017/01/02/14:00"
2018/05/03 01:53:29.344305 dir/server: Snapshotted "bambi@forest.earth/" into "bambi+snapshot@forest.earth/2017/01/02/17:01"
2018/05/03 01:53:29.350915 dir/server: Snapshotted "bambi@forest.earth/" into "bambi+snapshot@forest.earth/2017/01/02/17:02"
2018/05/03 01:53:29.361158 dir/server: Snapshotted "bambi@forest.earth/" into "bambi+snapshot@forest.earth/2017/01/02/17:03"
2018/05/03 01:53:29.374295 dir/server: Snapshotted "bambi@forest.earth/" into "bambi+snapshot@forest.earth/2017/01/02/17:13"
FAIL

Can you imagine how this might be related to this change? It looks flaky to me, although I'm surprised because this is the first time I've seen it, as far as I remember.

Patch-set: 7
Reviewer: Andrew Gerrand <5389@0759ed4b-3fdc-34dc-866b-f2e708168c03>