pack/ee/ee.go: Allow mixed key types with single EEPack.
*** This is an incompatible packdata format change.
*** Do not submit without coordinated wipe of existing directories.

Replace three existing packings with EEPack. Allow mixed keys,
so that owners and readers do not all have to synchronize their
preferred elliptic curves.  Think of packing=EEp256Pack as replaced by
packing=EEPack and curveName="p256".  Said yet another way, Alice
whose public key is on curve p384 can share with Bob whose public
key is on curve p256.

The owner's key determines the curve used for packdata signature.
In order to allow an owner to rotate keys without invalidating
reads during the repacking of all files, extend packdata to two
signatures.  Supplemental functions for efficient repacking will
come in a later CL.

One of the tests still fails, but I'll need to add some debug
flag to the test infrastructure to understand what's happening.
In the meantime, since this is such a big change, I'd welcome some
comments on the change.  In particular, I anticipate that we
may want variables like curveName to have a type CurveName but
am not sure, and am not sure if that goes in upspin or factotum.

In a future CL, User.Lookup() will change to return a single PublicKey
rather than a slice.

Here's the failing test:
--- FAIL: TestAllInProcess (0.03s)
	access_test.go:65: called from access_test.go:165 with ee packing:
	access_test.go:67: With Access file: Get
"user3@domain.com/public/public.txt" for user "user2@domain.com" failed
incorrectly: user3@domain.com/public/public.txt: Unpack: no wrapped key
for me

Still deciding where to add debug flag...
Also, I haven't yet added tests that exercise sharing with multiple readers
on different curves.

Change-Id: I81b683edd3971b4a1342fd96acfb2895d3e54387