Update patch set 1
Patch Set 1:

> > Where are you seeing the error?
 > > You may need to run upspin-deploy -create again for your cluster.
 > 
 > The error happens because of the new constants added for go1.8:
 > https://00e9e64bac2361799494c63ee6a404da0cac6a8c5fe49709be-apidata.googleusercontent.com/download/storage/v1/b/upspin-test-cdbuild/o/log-c98ebb57-fc9b-40a7-b533-6e142086f844.txt?qk=AD5uMEvMJS2RBpZVFVsMBGd4ZDxfokSkxCIDnMAYR8DCEQUliyDqCsfymbbCGsU3aRH2-yjUPMS_4bItFQEZZjYXbeo2d5UIqe3m9HMTAgjo8D186BZX-RHSs8AJLIlmU4K9KEAcD9QI9TduSS4aE4o0hv2k8m7mUmXmRLbXWlBUjrzkoYmK_S7gUBpmkjcAsjfsBxkUgTXNNg98apY9HoRv2NNi6Oc7fu417Thi8nL2EDVBTisVFPL-9v8GGsKQvh4JOQqgIiO9m-SXudo8F9S2ALzGbCnXZgWkdgF6PLWbxUzHCNzG3RfM2eTWTebGg4XEsVFLUZ_gH16c53t7MJ101Bs8mVmAoE6WpXjmxHCzTO_VfUbYLtTfaeG4qVzbFcSRXITPJOsxbyjb5-kD_zxZnVDnXD1rXGbtOYt8Mdd9Xz_OPmfGoTB8AhodcO3y3oC2uid4CGRLmmIQsZFWK-W8fpBrSgvIdfPmzcz42hxUk1rw6OsHAgqz6uXVNeNv4-RciWSoO_eazh7eL2LTT1FNTR0eY2zeiSARuFXb25royjEBX60qzmhyfvOotGyPqSJvsFCUIs_oacr-ctGcTedqNNzuSvxtxMNKfPbmy5j8vwmdouipCBAFsbiaT9EucQmi5-bJn2wq6LSchZKyhsVYoW9RyOlvNRvwjVoTNZCCvr-gxZC82eeMacqxuu77pOOpqE4ms7GDUjr1u3TH5mN5NFWcAXSggpJ3x7pRBCG6bXWdKiZst2KS7bN3aNPlUvgJXzthOWlMb2kCih4DHaCO5QHCuoVvVKAI0FLHbBwzxoIhJc-af9dS7lMKLsPA3lCveqJcJPY4

Here:
Step #0: src/upspin.io/cloud/https/https.go:167: undefined: tls.TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
Step #0: src/upspin.io/cloud/https/https.go:170: undefined: tls.TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
Step #0: src/upspin.io/cloud/https/https.go:174: undefined: tls.X25519

We decided to wait for GCP to upgrade to go 1.8 first and then re-introduce the CL or we can't deploy.

Patch-set: 1