Update patch set 6
Patch Set 6:

Yes, it's ready for review.

What's strange is that I don't see those errors. I just see this:

Running with -race fails, but not because of a detected race:

~/src/upspin.io/serverutil/perm $ go test -race
--- FAIL: TestDirIntegration (1.05s)
	dir_test.go:63: Expected root creation to succeed; instead err = user bob@uncle.com: serverutil/perm.Put: permission denied: user not authorized
FAIL
exit status 1
FAIL	upspin.io/serverutil/perm	8.280s

But running normally passes:

~/src/upspin.io/serverutil/perm $ go test
PASS
ok  	upspin.io/serverutil/perm	2.692s

I think I probably forgot to mail the most recent changeset, so please try cherry picking the latest version and let me know if you see the same thing. Very puzzling.

Patch-set: 6