shutdown: deflake test
On Linux we would occasionally see a failure like this:

--- FAIL: TestShutdown (1.06s)
    --- FAIL: TestShutdown/messy (0.03s)
        shutdown_test.go:119: child output ended, expected more lines

This was because the child process would be sent a SIGTERM before
it had a chance to register its shutdown handlers.
Fix this race condition by making the child print its "hello" message
after registering those handlers, not before.

Change-Id: I7907194080ead68deeae7f1788e8a068440b4229